[package]
name = "idaro"
version = "0.1.0"
authors = ["Thatguyjs"]
edition = "2021"

[dependencies]
clap = { version="3.1.12", features=["cargo"] }
ctrlc = "3.2.0"
pulldown-cmark = "0.9.1"
socket2 = "0.4.4"
